### ISSUE TITLE
Add links to the sidebar for Static Pages

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/agile-team-dashboard#55]
We want to add dynamically in the sidebar the links to static pages generated in `PagesController`.
* You can find the sidebar file in `app/views/shared/_sidebar.html.slim`

If you are not familiar with slim, have a look at [slim-lang](http://slim-lang.com/)

**Comment by bajajerk** [comment]
@DavidKang I would like to work on it , Can you elaborate a little bit more

**Comment by Ana06** [comment]
@bajajerk

>  would like to work on it

go ahead!

> Can you elaborate a little bit more
 
What is exactly not clear?

**Comment by Ana06** [comment]
@bajajerk 

> I would like to work on it 

go ahead! :wink: 

> Can you elaborate a little bit more

What is exactly not clear?
