### ISSUE TITLE
semantic-ui-sass shouldn't point to Github

### ISSUE THREAD

**Issue by Ana06** [openSUSE/agile-team-dashboard#58]
We are pointing here to github https://github.com/Ana06/agile-team-dashboard/blob/master/Gemfile#L17

@DavidKang you introduced this in your first commit and there is no explanation in the commit meesage. Do you have any clue here?

**Comment by DavidKang** [comment]
Because it's in the README of the project https://github.com/doabit/semantic-ui-sass#installation-and-usage

**Comment by Ana06** [comment]
ok, I'll ask them. But I would say we don't need this.

**Comment by DavidKang** [comment]
@Ana06, the owner of this gem has updated the README :smile_cat:

**Comment by Ana06** [comment]
But why do you close this? We are still pointing to github in our Gemfile!

**Comment by DavidKang** [comment]
Because you were asking :smile_cat:

**Comment by Ana06** [comment]
@DavidKang 

> Because you were asking 

hahaha yes, to remove it if it is not needed. Now we can remove it. :stuck_out_tongue_closed_eyes:

**Comment by bgeuken** [comment]
Then let's fix it! -> #66

**Comment by Ana06** [comment]
@bgeuken this issue was too easy for you! I would suggest that we do not implement the junior issues that are not very urgent, so other people can work on them :wink:
