### ISSUE TITLE
Change Sprint name by Sprint number

### ISSUE THREAD

**Issue by Ana06** [openSUSE/agile-team-dashboard#75]
It should be an integer and not an string anymore. It should be always present.

TASK FOR THE FUTURE:

- In the future we could try to generate one by default, by currently it is enough if it is introduced manually.

- The number of the Sprint should't be changed if the Sprint was already started.

**Comment by Ana06** [comment]
@DavidKang would you be that nice to take care of this? :wink:

**Comment by DavidKang** [comment]
@Ana06, sure!

**Comment by Ana06** [comment]
@DavidKang thanks!

BTW, this closes https://github.com/openSUSE/agile-team-dashboard/issues/46
