### ISSUE TITLE
Order sprints

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/agile-team-dashboard#85]
Now the sprints list looks like this:

![screenshot from 2017-11-08 15-45-48](https://user-images.githubusercontent.com/24919/32555248-87b57922-c49c-11e7-894f-1688958b4088.png)

It would be nice to provide a way to sort the sprints, or to sort them by start date.

**Comment by DavidKang** [comment]
Nice @eduardoj, could you make a PR 😸?

**Comment by Chaseshak** [comment]
@DavidKang Looking for a good first issue, can I take this issue?

**Comment by DavidKang** [comment]
@Chaseshak, sure 😄

**Comment by AnkushMalik** [comment]
umm its been more than a month since any activity on this issue , so i can make a take this issue ? 
@Chaseshak @Ana06  @DavidKang

**Comment by Ana06** [comment]
It seems @Chaseshak is not working on this anymore, so I hope it is fine with him. @AnkushMalik go ahead. :smile:
