### ISSUE TITLE
close icon doesnt closes the flash message

### ISSUE THREAD

**Issue by AnkushMalik** [openSUSE/agile-team-dashboard#95]
![image](https://user-images.githubusercontent.com/13421233/34431493-bc189dea-ec95-11e7-92dc-f0fa8af99aa0.png)

clicking on close (cross) icon should make the  flash message go away.
jquery slideup function may be.

**Comment by Ana06** [comment]
@AnkushMalik please add a description to your issue so we can know what is this exactly about 😉
